[package]
name = "hooker"
version = "0.1.0"
authors = ["Joey Hines <joey@ahines.net>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = "1.0.104"
serde_json = "1.0.44"
log = "0.4.8"
simplelog = "0.7.4"
actix-http = "1.0.1"
actix-service = "1.0.5"
